baseURL = 'https://nguyenthanhluan09060024.github.io/personal-blog/'
languageCode = 'vi-VN'
title = 'Blog Cá Nhân - Lập Trình Mạng'
theme = 'personal-blog-theme'

[params]
  author = "Nguyễn Thành Luân"
  description = "Blog cá nhân chia sẻ kiến thức về lập trình mạng với Java & JavaScript"
  email = "nguyenthanhluan0906200@gmail.com"
  phone = "0961107594"
  birthdate = "09/06/2004"
  experience = "3 năm"
  university = "Đại học Công nghệ TP.HCM"
  github = "nguyenthanhluan09060024"
  linkedin = "your-linkedin-username"
  
[menu]
  [[menu.main]]
    name = "Trang chủ"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Giới thiệu"
    url = "/about/"
    weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true